server {
    listen 80;
    server_name api.jsangho.cloud; # 본인 도메인 입력

    # Let's Encrypt 인증서 발급 검증용 경로
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # 모든 HTTP 요청을 HTTPS로 리다이렉트
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.jsangho.cloud; # 본인 도메인 입력

    # 발급받은 SSL 인증서 파일 위치
    ssl_certificate /etc/letsencrypt/live/api.jsangho.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.jsangho.cloud/privkey.pem;

    location / {
        # 백엔드 서버나 프론트엔드로 프록시 연결
        proxy_pass http://jsangho-container:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
