"""baseline sync migration history with live schema

Revision ID: 07a11683a53b
Revises:
Create Date: 2026-07-30 09:12:24.208152

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07a11683a53b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    자동생성된 diff 중 상점(shop_items·point_ledger_entries·user_shop_items)
    생성분만 남겼다. heyman(discord_messages·notifications·telegram_messages)
    테이블 신설과 wrestlers·demo_users·demo_jobs·receiver_emails DROP,
    passengers.passenger_id nullable 변경은 이번 상점 작업과 무관한 별개
    드리프트라 의도적으로 제외했다 — 특히 wrestlers·receiver_emails는 실제
    데이터가 있어 자동 DROP을 그대로 적용하면 안 된다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shop_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("is_consumable", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_shop_items_code"), "shop_items", ["code"], unique=True)
    op.create_table(
        "point_ledger_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("entry_type", sa.String(length=20), nullable=False),
        sa.Column("shop_item_id", sa.Integer(), nullable=True),
        sa.Column("memo", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shop_item_id"], ["shop_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_point_ledger_entries_user_id"),
        "point_ledger_entries",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_shop_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("shop_item_id", sa.Integer(), nullable=False),
        sa.Column("context_key", sa.String(length=80), nullable=False),
        sa.Column("is_equipped", sa.Boolean(), nullable=False),
        sa.Column(
            "acquired_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shop_item_id"], ["shop_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "shop_item_id", "context_key", name="uq_user_shop_item_context"
        ),
    )
    op.create_index(
        op.f("ix_user_shop_items_shop_item_id"),
        "user_shop_items",
        ["shop_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_shop_items_user_id"), "user_shop_items", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_shop_items_user_id"), table_name="user_shop_items")
    op.drop_index(op.f("ix_user_shop_items_shop_item_id"), table_name="user_shop_items")
    op.drop_table("user_shop_items")
    op.drop_index(
        op.f("ix_point_ledger_entries_user_id"), table_name="point_ledger_entries"
    )
    op.drop_table("point_ledger_entries")
    op.drop_index(op.f("ix_shop_items_code"), table_name="shop_items")
    op.drop_table("shop_items")
    # ### end Alembic commands ###
