"""WWE 활성 로스터 카탈로그 (`_docs/wwe_active_roster_cleaned.csv` 기준, Evolve 브랜드 제외).

기록 페이지 선수 명단과 실제이름·생년월일·키·몸무게 표시용 정적 데이터.
CSV가 갱신되면 이 파일도 함께 갱신해야 한다 (자동 동기화 없음).
"""

from __future__ import annotations

from typing import TypedDict

from kayfabe.app.services.competitor_roster import normalize_name

ROSTER_SOURCE = "wwe_active_roster_cleaned.csv (Evolve 브랜드 제외)"


class RosterEntry(TypedDict):
    name: str
    real_name: str | None
    height_cm: float | None
    weight_kg: float | None
    birth_date: str | None


WWE_ROSTER: list[RosterEntry] = [
    {
        "name": "Akira Tozawa",
        "real_name": "Akira Tozawa",
        "height_cm": 171.0,
        "weight_kg": 71.0,
        "birth_date": "1985-07-22",
    },
    {
        "name": "Angelo Dawkins",
        "real_name": "Gary Gordon",
        "height_cm": 196.0,
        "weight_kg": 120.0,
        "birth_date": "1990-07-24",
    },
    {
        "name": "Austin Theory",
        "real_name": "Austin Tyler White",
        "height_cm": 185.0,
        "weight_kg": 100.0,
        "birth_date": "1997-08-02",
    },
    {
        "name": "Tyler Bate",
        "real_name": "Tyler Bate",
        "height_cm": 170.0,
        "weight_kg": 80.0,
        "birth_date": "1997-03-07",
    },
    {
        "name": "Big Cass",
        "real_name": 'William "Bill" Morrissey',
        "height_cm": 193.0,
        "weight_kg": 140.0,
        "birth_date": "1986-08-16",
    },
    {
        "name": "Bron Breakker",
        "real_name": "Bronson Rechsteiner",
        "height_cm": 183.0,
        "weight_kg": 113.0,
        "birth_date": "1997-10-24",
    },
    {
        "name": "Bronson Reed",
        "real_name": "Jermaine Haley",
        "height_cm": 183.0,
        "weight_kg": 150.0,
        "birth_date": "1988-08-25",
    },
    {
        "name": "Brutus Creed",
        "real_name": "Drew Allan Kasper",
        "height_cm": 180.0,
        "weight_kg": 128.0,
        "birth_date": "1996-05-13",
    },
    {
        "name": "Chad Gable",
        "real_name": "Charles Edward Betts",
        "height_cm": 173.0,
        "weight_kg": 92.0,
        "birth_date": "1990-07-24",
    },
    {
        "name": "Cruz Del Toro",
        "real_name": "Raúl Mendoza",
        "height_cm": 178.0,
        "weight_kg": 75.0,
        "birth_date": "1991-09-16",
    },
    {
        "name": "Dominik Mysterio",
        "real_name": "Dominik Óscar Gutiérrez",
        "height_cm": 185.0,
        "weight_kg": 81.0,
        "birth_date": "1997-04-05",
    },
    {
        "name": "Dragon Lee",
        "real_name": "??? Muñoz González",
        "height_cm": 171.0,
        "weight_kg": 75.0,
        "birth_date": "1995-05-15",
    },
    {
        "name": "Ludwig Kaiser",
        "real_name": "Marcel Barthel",
        "height_cm": 191.0,
        "weight_kg": 95.0,
        "birth_date": "1991-07-08",
    },
    {
        "name": "Erik",
        "real_name": "Raymond Rowe",
        "height_cm": 185.0,
        "weight_kg": 112.0,
        "birth_date": "1984-08-21",
    },
    {
        "name": "Ethan Page",
        "real_name": "Julian Micevski",
        "height_cm": 188.0,
        "weight_kg": 109.0,
        "birth_date": "1989-09-20",
    },
    {
        "name": "Grayson Waller",
        "real_name": "Matthew Farrelly",
        "height_cm": 190.0,
        "weight_kg": 91.0,
        "birth_date": "1990-03-21",
    },
    {
        "name": "Ivar",
        "real_name": "Todd James Smith",
        "height_cm": 188.0,
        "weight_kg": 138.0,
        "birth_date": "1984-03-03",
    },
    {
        "name": "Jacob Fatu",
        "real_name": "Jacob Samuel Fatu",
        "height_cm": 185.0,
        "weight_kg": 127.0,
        "birth_date": None,
    },
    {
        "name": "JD McDonagh",
        "real_name": "Jordan Devlin",
        "height_cm": 178.0,
        "weight_kg": 82.0,
        "birth_date": "1990-03-15",
    },
    {
        "name": "Je'Von Evans",
        "real_name": "Malachi Jeffers",
        "height_cm": 188.0,
        "weight_kg": 77.0,
        "birth_date": "2004-04-29",
    },
    {
        "name": "Jey Uso",
        "real_name": "Joshua Samuel Fatu",
        "height_cm": 183.0,
        "weight_kg": 103.0,
        "birth_date": "1985-08-22",
    },
    {
        "name": "Jimmy Uso",
        "real_name": "Jonathan Solofa Fatu",
        "height_cm": 187.0,
        "weight_kg": 114.0,
        "birth_date": "1985-08-22",
    },
    {
        "name": "Joaquin Wilde",
        "real_name": "Michael Paris",
        "height_cm": 173.0,
        "weight_kg": 82.0,
        "birth_date": "1986-10-05",
    },
    {
        "name": "Joe Hendry",
        "real_name": "Joe Samuel Hendry",
        "height_cm": 185.0,
        "weight_kg": 104.0,
        "birth_date": "1988-05-01",
    },
    {
        "name": "Julius creed",
        "real_name": "Jacob Andrew Kasper",
        "height_cm": 191.0,
        "weight_kg": 104.0,
        "birth_date": "1994-10-03",
    },
    {
        "name": "LA Knight",
        "real_name": "Shaun Edward Ricker",
        "height_cm": 185.0,
        "weight_kg": 106.0,
        "birth_date": "1982-11-01",
    },
    {
        "name": "Logan Paul",
        "real_name": "Logan Alexander Paul",
        "height_cm": 188.0,
        "weight_kg": 86.0,
        "birth_date": "1995-04-01",
    },
    {
        "name": "Montez Ford",
        "real_name": "Kenneth Crawford",
        "height_cm": 183.0,
        "weight_kg": 105.0,
        "birth_date": "1990-05-31",
    },
    {
        "name": "Oba Femi",
        "real_name": "Isaac Odugbesan",
        "height_cm": 193.0,
        "weight_kg": 140.0,
        "birth_date": "1998-04-22",
    },
    {
        "name": "Otis",
        "real_name": "Nikola Bogojevic",
        "height_cm": 178.0,
        "weight_kg": 150.0,
        "birth_date": "1991-12-21",
    },
    {
        "name": "Penta",
        "real_name": None,
        "height_cm": 180.0,
        "weight_kg": 87.0,
        "birth_date": "1985-02-26",
    },
    {
        "name": "Pete Dunne",
        "real_name": "Peter Thomas England",
        "height_cm": 178.0,
        "weight_kg": 93.0,
        "birth_date": "1993-11-09",
    },
    {
        "name": "Rey Mysterio",
        "real_name": "Óscar Gutiérrez Rubio",
        "height_cm": 168.0,
        "weight_kg": 79.0,
        "birth_date": "1974-12-11",
    },
    {
        "name": "Roman Reigns",
        "real_name": "Leati Joseph Anoa'i",
        "height_cm": 190.0,
        "weight_kg": 120.0,
        "birth_date": "1985-05-25",
    },
    {
        "name": "Rusev",
        "real_name": "Miroslav Petrov Barnyashev",
        "height_cm": 183.0,
        "weight_kg": 122.0,
        "birth_date": "1984-12-25",
    },
    {
        "name": "Seth Rollins",
        "real_name": "Colby Daniel Lopez",
        "height_cm": 185.0,
        "weight_kg": 93.0,
        "birth_date": "1986-05-28",
    },
    {
        "name": "AJ Lee",
        "real_name": "April Jeanette Brooks",
        "height_cm": 158.0,
        "weight_kg": 52.0,
        "birth_date": "1987-03-19",
    },
    {
        "name": "Asuka",
        "real_name": "Kanako Urai",
        "height_cm": 160.0,
        "weight_kg": 62.0,
        "birth_date": "1981-09-26",
    },
    {
        "name": "Bayley",
        "real_name": "Pamela Rose Martinez",
        "height_cm": 170.0,
        "weight_kg": 64.0,
        "birth_date": "1989-06-15",
    },
    {
        "name": "Becky Lynch",
        "real_name": "Rebecca Quin",
        "height_cm": 168.0,
        "weight_kg": 61.0,
        "birth_date": "1987-01-30",
    },
    {
        "name": "Brie Bella",
        "real_name": "Brianna Monique Danielson",
        "height_cm": 168.0,
        "weight_kg": None,
        "birth_date": "1983-11-21",
    },
    {
        "name": "Ivy Nile",
        "real_name": "Emily Andzulis",
        "height_cm": 157.0,
        "weight_kg": 57.0,
        "birth_date": "1992-02-26",
    },
    {
        "name": "Iyo Sky",
        "real_name": "Masami Odate",
        "height_cm": 156.0,
        "weight_kg": 54.0,
        "birth_date": "1990-05-08",
    },
    {
        "name": "Liv Morgan",
        "real_name": "Gionna Jene Daddio",
        "height_cm": 160.0,
        "weight_kg": 52.0,
        "birth_date": "1994-06-08",
    },
    {
        "name": "Lyra Valkyria",
        "real_name": "Aoife Marie Cusack",
        "height_cm": 167.0,
        "weight_kg": 59.0,
        "birth_date": "1996-10-23",
    },
    {
        "name": "Maxxine Dupri",
        "real_name": "Sydney Jeannine Zmrzel",
        "height_cm": 173.0,
        "weight_kg": 61.0,
        "birth_date": "1997-05-19",
    },
    {
        "name": "Nattie",
        "real_name": "Natalie Katherine Neidhart",
        "height_cm": 166.0,
        "weight_kg": 61.0,
        "birth_date": "1982-05-27",
    },
    {
        "name": "Nikki Bella",
        "real_name": "Nicola Mariel Garcia-Colace",
        "height_cm": 168.0,
        "weight_kg": None,
        "birth_date": "1983-11-21",
    },
    {
        "name": "Raquel Rodriguez",
        "real_name": "Victoria González",
        "height_cm": 187.0,
        "weight_kg": 85.0,
        "birth_date": "1991-01-12",
    },
    {
        "name": "Roxanne Perez",
        "real_name": "Carla Gonzalez",
        "height_cm": 155.0,
        "weight_kg": 52.0,
        "birth_date": "2001-11-05",
    },
    {
        "name": "Sol Ruca",
        "real_name": "Calyx Harmony Hampton",
        "height_cm": 173.0,
        "weight_kg": 63.0,
        "birth_date": "1999-08-26",
    },
    {
        "name": "Stepahnie Vaquer",
        "real_name": "Ana Stephanie Vaquer González",
        "height_cm": 160.0,
        "weight_kg": 50.0,
        "birth_date": "1993-03-29",
    },
    {
        "name": "Angel",
        "real_name": "Humberto Garza Solano",
        "height_cm": 181.0,
        "weight_kg": 93.0,
        "birth_date": "1992-09-23",
    },
    {
        "name": "Axiom",
        "real_name": "Carlos Ruíz",
        "height_cm": 173.0,
        "weight_kg": 70.0,
        "birth_date": "1997-05-09",
    },
    {
        "name": "Baron Corbin",
        "real_name": "Thomas Pestock",
        "height_cm": 200.0,
        "weight_kg": 129.0,
        "birth_date": "1984-09-13",
    },
    {
        "name": "Berto",
        "real_name": "Humberto Garza Carrillo",
        "height_cm": 185.0,
        "weight_kg": 90.0,
        "birth_date": "1995-10-20",
    },
    {
        "name": "Carmelo Hayes",
        "real_name": "Christian Brigham",
        "height_cm": 172.0,
        "weight_kg": 95.0,
        "birth_date": "1994-08-01",
    },
    {
        "name": "CM Punk",
        "real_name": "Phillip Jack Brooks",
        "height_cm": 185.0,
        "weight_kg": 99.0,
        "birth_date": "1978-10-26",
    },
    {
        "name": "Cody Rhodes",
        "real_name": "Cody Garrett Runnels",
        "height_cm": 188.0,
        "weight_kg": 98.0,
        "birth_date": "1985-06-30",
    },
    {
        "name": "Damian Priest",
        "real_name": "Luis Martinez",
        "height_cm": 196.0,
        "weight_kg": 113.0,
        "birth_date": "1982-09-26",
    },
    {
        "name": "Drew McIntyre",
        "real_name": "Andrew McLean Galloway IV",
        "height_cm": 197.0,
        "weight_kg": 125.0,
        "birth_date": "1985-06-06",
    },
    {
        "name": "Elton Prince",
        "real_name": "Lewis Howley",
        "height_cm": 185.0,
        "weight_kg": 78.0,
        "birth_date": "1997-05-21",
    },
    {
        "name": "Finn Bálor",
        "real_name": "Fergal Devitt",
        "height_cm": 180.0,
        "weight_kg": 86.0,
        "birth_date": "1981-07-25",
    },
    {
        "name": "Gunther",
        "real_name": "Walter Hahn",
        "height_cm": 194.0,
        "weight_kg": 119.0,
        "birth_date": "1987-08-20",
    },
    {
        "name": "Ilja Dragunov",
        "real_name": "Ilja Rukober",
        "height_cm": 178.0,
        "weight_kg": 95.0,
        "birth_date": "1993-10-10",
    },
    {
        "name": "Johnny Gargano",
        "real_name": "John Anthony Nicholas Gargano",
        "height_cm": 174.0,
        "weight_kg": 90.0,
        "birth_date": "1987-08-14",
    },
    {
        "name": "Kevin Owens",
        "real_name": "Kevin Yanick Steen",
        "height_cm": 178.0,
        "weight_kg": 121.0,
        "birth_date": "1984-05-07",
    },
    {
        "name": "Kit Wilson",
        "real_name": "Samuel Stoker",
        "height_cm": 180.0,
        "weight_kg": 79.0,
        "birth_date": "1994-08-04",
    },
    {
        "name": "Matt Cardona",
        "real_name": "Matthew Brett Cardona Jr.",
        "height_cm": 188.0,
        "weight_kg": 101.0,
        "birth_date": "1985-05-14",
    },
    {
        "name": "The Miz",
        "real_name": "Michael Gregory Mizanin",
        "height_cm": 185.0,
        "weight_kg": 100.0,
        "birth_date": "1980-10-08",
    },
    {
        "name": "Nathan Frazer",
        "real_name": "Benjamin Carter",
        "height_cm": 178.0,
        "weight_kg": 83.0,
        "birth_date": "1998-07-23",
    },
    {
        "name": "R-Truth",
        "real_name": "Ronnie Aaron Killings",
        "height_cm": 188.0,
        "weight_kg": 100.0,
        "birth_date": "1972-01-10",
    },
    {
        "name": "Randy Orton",
        "real_name": "Randal Keith Orton",
        "height_cm": 196.0,
        "weight_kg": 131.5,
        "birth_date": "1980-04-01",
    },
    {
        "name": "Rey Fénix",
        "real_name": None,
        "height_cm": 177.0,
        "weight_kg": 83.0,
        "birth_date": "1990-12-30",
    },
    {
        "name": "Ricky Saints",
        "real_name": "Richard Starks",
        "height_cm": 183.0,
        "weight_kg": 88.0,
        "birth_date": "1990-02-21",
    },
    {
        "name": "Royce Keys",
        "real_name": "William Hobson",
        "height_cm": 185.0,
        "weight_kg": 122.0,
        "birth_date": "1985-01-23",
    },
    {
        "name": "Sami Zayn",
        "real_name": "Rami Sebei",
        "height_cm": 185.0,
        "weight_kg": 96.0,
        "birth_date": "1984-07-12",
    },
    {
        "name": "Shinsuke Nakamura",
        "real_name": "Shinsuke Nakamura",
        "height_cm": 188.0,
        "weight_kg": 104.0,
        "birth_date": "1980-02-24",
    },
    {
        "name": "Solo Sikoa",
        "real_name": "Joseph Yokozuna Fatu",
        "height_cm": 181.0,
        "weight_kg": 110.0,
        "birth_date": "1993-03-18",
    },
    {
        "name": "Talla Tonga",
        "real_name": "Taula Tautuiaki Koloamatangi",
        "height_cm": 206.0,
        "weight_kg": 120.0,
        "birth_date": "1991-02-07",
    },
    {
        "name": "Tama Tonga",
        "real_name": "Alipate Aloisio Leone",
        "height_cm": 183.0,
        "weight_kg": 95.0,
        "birth_date": "1982-10-15",
    },
    {
        "name": "Trick Williams",
        "real_name": "Matrick Mondre Belton",
        "height_cm": 193.0,
        "weight_kg": 113.0,
        "birth_date": "1994-05-26",
    },
    {
        "name": "Alexa Bliss",
        "real_name": "Alexis Cabrera",
        "height_cm": 155.0,
        "weight_kg": 46.0,
        "birth_date": "1991-08-09",
    },
    {
        "name": "B-Fab",
        "real_name": "Briana Brandy",
        "height_cm": 175.0,
        "weight_kg": 62.0,
        "birth_date": "1990-11-22",
    },
    {
        "name": "Bianca Belair",
        "real_name": "Bianca Blair Crawford",
        "height_cm": 170.0,
        "weight_kg": 75.0,
        "birth_date": "1989-04-09",
    },
    {
        "name": "Blake Monroe",
        "real_name": "Mariah May Mead",
        "height_cm": 173.0,
        "weight_kg": 64.0,
        "birth_date": "1998-08-04",
    },
    {
        "name": "Candice LeRae",
        "real_name": "Candice Gargano",
        "height_cm": 157.0,
        "weight_kg": 50.0,
        "birth_date": "1985-09-25",
    },
    {
        "name": "Charlotte Flair",
        "real_name": "Ashley Elizabeth Fliehr",
        "height_cm": 178.0,
        "weight_kg": 68.0,
        "birth_date": "1986-04-05",
    },
    {
        "name": "Chelsea Green",
        "real_name": "Chelsea Anne Cardona",
        "height_cm": 170.0,
        "weight_kg": 57.0,
        "birth_date": "1991-04-04",
    },
    {
        "name": "Fallon Henley",
        "real_name": "Theresa Lee Schuessler",
        "height_cm": 170.0,
        "weight_kg": None,
        "birth_date": "1994-09-25",
    },
    {
        "name": "Giulia",
        "real_name": "Eimi Gloria Matsudo",
        "height_cm": 162.0,
        "weight_kg": 55.0,
        "birth_date": "1994-02-21",
    },
    {
        "name": "Jacy Jayne",
        "real_name": "Taylor Grado",
        "height_cm": 168.0,
        "weight_kg": 52.0,
        "birth_date": "1996-06-02",
    },
    {
        "name": "Jade Cargill",
        "real_name": "Jade Cargill",
        "height_cm": 178.0,
        "weight_kg": 73.0,
        "birth_date": None,
    },
    {
        "name": "Jordynne Grace",
        "real_name": "Patricia Forrest Parker",
        "height_cm": 160.0,
        "weight_kg": 71.0,
        "birth_date": None,
    },
    {
        "name": "Kiana James",
        "real_name": "Kayla Klingensmith",
        "height_cm": 173.0,
        "weight_kg": None,
        "birth_date": "1997-05-23",
    },
    {
        "name": "Lainey Reid",
        "real_name": "Tylynn Register",
        "height_cm": 167.0,
        "weight_kg": 61.0,
        "birth_date": "1998-10-02",
    },
    {
        "name": "Lash Legend",
        "real_name": "Anriel Howard",
        "height_cm": 183.0,
        "weight_kg": 109.0,
        "birth_date": "1997-05-06",
    },
    {
        "name": "Michin",
        "real_name": "Stephanie Hym Lee",
        "height_cm": 170.0,
        "weight_kg": 60.0,
        "birth_date": "1989-04-16",
    },
    {
        "name": "Nia Jax",
        "real_name": 'Savelina "Lina" Fanene',
        "height_cm": 183.0,
        "weight_kg": 116.0,
        "birth_date": "1984-05-29",
    },
    {
        "name": "Naomi",
        "real_name": "Trinity McCray Fatu",
        "height_cm": 165.0,
        "weight_kg": 57.0,
        "birth_date": "1987-11-30",
    },
    {
        "name": "Piper Niven",
        "real_name": "Kimberly Benson",
        "height_cm": 166.0,
        "weight_kg": 94.0,
        "birth_date": "1991-05-06",
    },
    {
        "name": "Rhea Ripley",
        "real_name": "Demi Bennett",
        "height_cm": 175.0,
        "weight_kg": 77.0,
        "birth_date": "1996-10-11",
    },
    {
        "name": "Tiffany Stratton",
        "real_name": "Jessica Lynn Woynilko",
        "height_cm": 171.0,
        "weight_kg": 65.0,
        "birth_date": "1999-05-01",
    },
    {
        "name": "Brock Lesnar",
        "real_name": "Brock Edward Lesnar",
        "height_cm": 191.0,
        "weight_kg": 129.0,
        "birth_date": "1977-07-12",
    },
    {
        "name": "Danhausen",
        "real_name": "Donovan Andrew Danhausen",
        "height_cm": 178.0,
        "weight_kg": 82.0,
        "birth_date": "1990-08-17",
    },
    {
        "name": "Omos",
        "real_name": 'Tolulope "Jordan" Omogbehin',
        "height_cm": 221.0,
        "weight_kg": 189.0,
        "birth_date": "1994-05-16",
    },
    {
        "name": "Paige",
        "real_name": "Saraya-Jade Bevis",
        "height_cm": 174.0,
        "weight_kg": 54.0,
        "birth_date": "1992-08-17",
    },
    {
        "name": "Brad Baylor",
        "real_name": None,
        "height_cm": None,
        "weight_kg": None,
        "birth_date": None,
    },
    {
        "name": "Bronco Nima",
        "real_name": "Edwin Grande",
        "height_cm": 196.0,
        "weight_kg": 135.0,
        "birth_date": "2001-12-12",
    },
    {
        "name": "Brooks Jensen",
        "real_name": "Benjamin Buchanan",
        "height_cm": 196.0,
        "weight_kg": 110.0,
        "birth_date": "2001-08-21",
    },
    {
        "name": 'Channing "Stacks" Lorenzo',
        "real_name": "Mitchell LaValley",
        "height_cm": 183.0,
        "weight_kg": 93.0,
        "birth_date": "1997-03-03",
    },
    {
        "name": "Charlie Dempsey",
        "real_name": "Bailey Matthews",
        "height_cm": 185.0,
        "weight_kg": 94.0,
        "birth_date": "1996-12-30",
    },
    {
        "name": "Cruz Montana",
        "real_name": "Mark Sanchez",
        "height_cm": 178.0,
        "weight_kg": 89.0,
        "birth_date": "1991-02-04",
    },
    {
        "name": "Cutler James",
        "real_name": "Jonah C. Niesenbaum",
        "height_cm": 196.0,
        "weight_kg": 118.0,
        "birth_date": "2000-11-16",
    },
    {
        "name": "Dion Lennox",
        "real_name": "Andrzej Hughes-Murray",
        "height_cm": 188.0,
        "weight_kg": 110.0,
        "birth_date": "1998-01-16",
    },
    {
        "name": "Dorian Van Dux",
        "real_name": "Mike Derudder",
        "height_cm": 180.0,
        "weight_kg": 110.0,
        "birth_date": "1996-05-07",
    },
    {
        "name": "EK Prosper",
        "real_name": None,
        "height_cm": None,
        "weight_kg": None,
        "birth_date": None,
    },
    {
        "name": "Elio LeFleur",
        "real_name": "Cyril Coquerelle",
        "height_cm": 180.0,
        "weight_kg": 70.0,
        "birth_date": "1999-02-19",
    },
    {
        "name": "Hank Walker",
        "real_name": "Joseph Sculthorpe",
        "height_cm": 191.0,
        "weight_kg": 139.0,
        "birth_date": "1998-06-11",
    },
    {
        "name": "Jackson Drake",
        "real_name": None,
        "height_cm": 183.0,
        "weight_kg": 78.0,
        "birth_date": None,
    },
    {
        "name": "Jasper Troy",
        "real_name": "Antione K Frazier",
        "height_cm": 196.0,
        "weight_kg": 150.0,
        "birth_date": "1998-05-20",
    },
    {
        "name": "Josh Briggs",
        "real_name": "Joshua Bruns",
        "height_cm": 203.0,
        "weight_kg": 122.0,
        "birth_date": "1993-03-05",
    },
    {
        "name": "Kale Dixon",
        "real_name": "Caleb J. Balgaard",
        "height_cm": 190.0,
        "weight_kg": 99.0,
        "birth_date": "1998-05-04",
    },
    {
        "name": "Kam Hendrix",
        "real_name": "Anthony Luke",
        "height_cm": 190.0,
        "weight_kg": 120.0,
        "birth_date": "1996-11-11",
    },
    {
        "name": "Keanu Carver",
        "real_name": "Kevin Isaiah Robertson",
        "height_cm": 187.0,
        "weight_kg": 131.0,
        "birth_date": None,
    },
    {
        "name": "Lexis King",
        "real_name": "Brian Zachary Pillman",
        "height_cm": 185.0,
        "weight_kg": 93.0,
        "birth_date": "1993-09-09",
    },
    {
        "name": "Lince Dorado",
        "real_name": "Jose Cordero",
        "height_cm": 170.0,
        "weight_kg": 76.0,
        "birth_date": "1987-05-11",
    },
    {
        "name": "Lucien Price",
        "real_name": "Nnamdi Oguayo",
        "height_cm": 190.0,
        "weight_kg": 111.0,
        "birth_date": "1997-01-12",
    },
    {
        "name": "Mason Rook",
        "real_name": "William Walker",
        "height_cm": 193.0,
        "weight_kg": 135.0,
        "birth_date": "1996-10-28",
    },
    {
        "name": "Myles Borne",
        "real_name": "David Bostian III",
        "height_cm": 188.0,
        "weight_kg": 103.0,
        "birth_date": "1999-05-25",
    },
    {
        "name": "NARAKU",
        "real_name": "Takaaki Watanabe",
        "height_cm": 178.0,
        "weight_kg": 106.0,
        "birth_date": "1987-01-26",
    },
    {
        "name": "Niko Vance",
        "real_name": "Skylor Clinton",
        "height_cm": 188.0,
        "weight_kg": 109.0,
        "birth_date": "1999-01-15",
    },
    {
        "name": "Noam Dar",
        "real_name": "Noam Dar",
        "height_cm": 176.0,
        "weight_kg": 81.0,
        "birth_date": "1993-07-28",
    },
    {
        "name": "Osiris Griffin",
        "real_name": "Joshua Black",
        "height_cm": 190.0,
        "weight_kg": 132.0,
        "birth_date": "1997-12-25",
    },
    {
        "name": "Ricky Smokes",
        "real_name": None,
        "height_cm": None,
        "weight_kg": None,
        "birth_date": None,
    },
    {
        "name": "Romeo Moreno",
        "real_name": "Jaime Zozaya-García",
        "height_cm": 190.0,
        "weight_kg": 90.0,
        "birth_date": "2002-07-11",
    },
    {
        "name": "Saquon Shugars",
        "real_name": "Copeland Barbee",
        "height_cm": 185.0,
        "weight_kg": 101.0,
        "birth_date": "2000-04-30",
    },
    {
        "name": "Sean Legacy",
        "real_name": "Sean Rossini",
        "height_cm": 180.0,
        "weight_kg": 94.0,
        "birth_date": "1995-11-28",
    },
    {
        "name": "Shawn Spears",
        "real_name": "Ronnie William Arneill",
        "height_cm": 191.0,
        "weight_kg": 101.0,
        "birth_date": "1981-02-19",
    },
    {
        "name": "Shiloh Hill",
        "real_name": "Thunder Justice Keck",
        "height_cm": 190.0,
        "weight_kg": 105.0,
        "birth_date": "1999-02-04",
    },
    {
        "name": "Tank Ledger",
        "real_name": "Joe Spivak",
        "height_cm": 180.0,
        "weight_kg": 136.0,
        "birth_date": "1999-10-11",
    },
    {
        "name": "Tate Wilder",
        "real_name": "Case Hatch",
        "height_cm": 182.0,
        "weight_kg": 104.0,
        "birth_date": None,
    },
    {
        "name": "Tavion Heights",
        "real_name": "G'Angelo Hancock",
        "height_cm": 185.0,
        "weight_kg": 97.0,
        "birth_date": "1997-07-27",
    },
    {
        "name": "Tony D'Angelo",
        "real_name": "Joseph Ariola",
        "height_cm": 183.0,
        "weight_kg": 110.0,
        "birth_date": "1995-06-09",
    },
    {
        "name": "Tristan Angels",
        "real_name": "Nathaniel Cranton",
        "height_cm": 190.0,
        "weight_kg": None,
        "birth_date": "2003-06-09",
    },
    {
        "name": "Uriah Connors",
        "real_name": "Brogan Finlay",
        "height_cm": 185.0,
        "weight_kg": 91.0,
        "birth_date": "2002-08-06",
    },
    {
        "name": "Adriana Rizzo",
        "real_name": "Anna Jade Keefer",
        "height_cm": 165.0,
        "weight_kg": 54.0,
        "birth_date": "1998-12-26",
    },
    {
        "name": "Arianna Grace",
        "real_name": "Bianca Sophia Carelli",
        "height_cm": 170.0,
        "weight_kg": 63.0,
        "birth_date": "1995-06-29",
    },
    {
        "name": "Izzi Dame",
        "real_name": "Franki Carissa Strefling",
        "height_cm": 178.0,
        "weight_kg": 65.0,
        "birth_date": "1999-07-13",
    },
    {
        "name": "Jaida Parker",
        "real_name": "Tiana Lillian Marie Caffey",
        "height_cm": 170.0,
        "weight_kg": None,
        "birth_date": "1999-02-12",
    },
    {
        "name": "Kali Armstrong",
        "real_name": "Destinee Brown",
        "height_cm": 165.0,
        "weight_kg": None,
        "birth_date": "1994-07-06",
    },
    {
        "name": "Karmen Petrovic",
        "real_name": "Monika Klisara",
        "height_cm": 165.0,
        "weight_kg": 54.0,
        "birth_date": "1995-10-29",
    },
    {
        "name": "Kelani Jordan",
        "real_name": "Lea Simone Mitchell",
        "height_cm": 165.0,
        "weight_kg": None,
        "birth_date": "1998-10-22",
    },
    {
        "name": "Kendal Grey",
        "real_name": "Peyton Prussin",
        "height_cm": 163.0,
        "weight_kg": None,
        "birth_date": "2001-06-15",
    },
    {
        "name": "Layla Diggs",
        "real_name": "Breanna Covington",
        "height_cm": None,
        "weight_kg": None,
        "birth_date": None,
    },
    {
        "name": "Lizzy Rain",
        "real_name": "Rayne Leat",
        "height_cm": 170.0,
        "weight_kg": 60.0,
        "birth_date": "1998-01-12",
    },
    {
        "name": "Lola Vice",
        "real_name": "Valerie Loureda",
        "height_cm": 163.0,
        "weight_kg": 57.0,
        "birth_date": "1998-07-19",
    },
    {
        "name": "Myka Lockwood",
        "real_name": "PBayley Humphrey",
        "height_cm": 178.0,
        "weight_kg": None,
        "birth_date": "2001-06-07",
    },
    {
        "name": "Nikkita Lyons",
        "real_name": "Faith Marie Jefferies",
        "height_cm": 173.0,
        "weight_kg": 70.0,
        "birth_date": "1999-08-05",
    },
    {
        "name": "Reina Volcán",
        "real_name": "Nicole Ripoll Martinez",
        "height_cm": None,
        "weight_kg": None,
        "birth_date": "1997-01-28",
    },
    {
        "name": "Skylar Raye",
        "real_name": "Danielle Raye Sekelsky",
        "height_cm": None,
        "weight_kg": None,
        "birth_date": "2001-06-30",
    },
    {
        "name": "Tatum Paxley",
        "real_name": "Natalie Elizabeth Beidelschies",
        "height_cm": 165.0,
        "weight_kg": 55.0,
        "birth_date": "1996-10-29",
    },
    {
        "name": "Thea Hail",
        "real_name": "Madison Knisley",
        "height_cm": 165.0,
        "weight_kg": 57.0,
        "birth_date": "2003-09-09",
    },
    {
        "name": "Wendy Choo",
        "real_name": "Karen Yu",
        "height_cm": 157.0,
        "weight_kg": None,
        "birth_date": "1992-01-18",
    },
    {
        "name": "Wren Sinclair",
        "real_name": "Madison Dombkowski",
        "height_cm": 168.0,
        "weight_kg": None,
        "birth_date": "1995-05-25",
    },
    {
        "name": "Zaria",
        "real_name": "Daria Hodder",
        "height_cm": 173.0,
        "weight_kg": 75.0,
        "birth_date": "1999-05-11",
    },
]

WWE_ROSTER_NAMES: list[str] = sorted({normalize_name(e["name"]) for e in WWE_ROSTER})

ROSTER_BY_NAME: dict[str, RosterEntry] = {
    normalize_name(entry["name"]): entry for entry in WWE_ROSTER
}


def get_roster_entry(name: str) -> RosterEntry | None:
    return ROSTER_BY_NAME.get(normalize_name(name))
